# project:
#   type: website
#   output-dir: docs
  
# book:
#   title: DanceOn Curriculum
#   author: Shuang
#   logo: 
#   repo-url: https://owochel.github.io/DanceOnE-Textbook/
#   repo-branch: master
#   repo-actions: [issue]
#   sharing: [twitter, facebook]
  
#   chapters:
#     - part: Introduction
#         - index.ipynb
#     - part: Curriculum
#       chapters:
#         - basics.ipynb
#         - cordinatesPractice.ipynb
#     # - part: Support
#     #   chapters:
#     #     - cordinatesPractice.ipynb

# format:
#   html:
#     theme: cosmo



project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction to DanceOn"
        contents:
          - index.ipynb

      - section: "Curriculum"
        contents:
          - basics.ipynb
          - cordinatesPractice.ipynb
    # - section: Support
    #       contents:
    #     - cordinatesPractice.ipynb
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

