project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction to danceON"
        contents:
          - index.ipynb

#       - section: "Curriculum"
#         contents:
#           - interfaces.ipynb
#           - cordinatesPractice.ipynb
#           - observation.ipynb
      - section: "Session 1"
        contents:
          - interfacesWorkshop.ipynb
          - cordinatesWorkshop.ipynb
      - section: "Session 2"
        contents:
          - whenConditionWorkshop.ipynb
      - section: "Session 3"
        contents:
         - distanceWorkshop.ipynb
         - observationWorkshop.ipynb
      # - section: "Session 4"
      #   contents:
      #    - observationWorkshop.ipynb
      # - section: "Session 5"
      #   contents:
      #    - observationWorkshop.ipynb
    # - section: Support
    #       contents:
    #     - cordinatesPractice.ipynb
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

