project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction to danceON"
        contents:
          - index.ipynb

#       - section: "Curriculum"
#         contents:
#           - interfaces.ipynb
#           - cordinatesPractice.ipynb
#           - observation.ipynb
      - section: "Co-Desgin Workshop"
        contents:
          - interfacesWorkshop.ipynb
          - cordinatesWorkshop.ipynb
          - observationWorkshop.ipynb
    # - section: Support
    #       contents:
    #     - cordinatesPractice.ipynb
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

