project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction to DanceOn"
        contents:
          - index.ipynb

      - section: "Curriculum"
        contents:
          - basics.ipynb
          - cordinatesPractice.ipynb
    # - section: Support
    #       contents:
    #     - cordinatesPractice.ipynb
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

